# CMAKE generated file: DO NOT EDIT!
# Generated by "NMake Makefiles" Generator, CMake Version 3.20

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

!IF "$(OS)" == "Windows_NT"
NULL=
!ELSE
NULL=nul
!ENDIF
SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\JetBrains\CLion 2021.2.3\bin\cmake\win\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\JetBrains\CLion 2021.2.3\bin\cmake\win\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:\ABCgpp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\ABCgpp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	echo >nul && "C:\Program Files\JetBrains\CLion 2021.2.3\bin\cmake\win\bin\cmake.exe" -E echo "No interactive CMake dialog available."
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache\fast: edit_cache
.PHONY : edit_cache\fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	echo >nul && "C:\Program Files\JetBrains\CLion 2021.2.3\bin\cmake\win\bin\cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache\fast: rebuild_cache
.PHONY : rebuild_cache\fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:\ABCgpp\CMakeFiles C:\ABCgpp\\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) all
	$(CMAKE_COMMAND) -E cmake_progress_start C:\ABCgpp\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) clean
.PHONY : clean

# The main clean target
clean\fast: clean
.PHONY : clean\fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall\fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) preinstall
.PHONY : preinstall\fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named program

# Build rule for target.
program: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) program
.PHONY : program

# fast build rule for target.
program\fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\program.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\program.dir\build
.PHONY : program\fast

algorithms\algorithms.obj: algorithms\algorithms.cpp.obj
.PHONY : algorithms\algorithms.obj

# target to build an object file
algorithms\algorithms.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\program.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\program.dir\algorithms\algorithms.cpp.obj
.PHONY : algorithms\algorithms.cpp.obj

algorithms\algorithms.i: algorithms\algorithms.cpp.i
.PHONY : algorithms\algorithms.i

# target to preprocess a source file
algorithms\algorithms.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\program.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\program.dir\algorithms\algorithms.cpp.i
.PHONY : algorithms\algorithms.cpp.i

algorithms\algorithms.s: algorithms\algorithms.cpp.s
.PHONY : algorithms\algorithms.s

# target to generate assembly for a file
algorithms\algorithms.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\program.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\program.dir\algorithms\algorithms.cpp.s
.PHONY : algorithms\algorithms.cpp.s

container\container.obj: container\container.cpp.obj
.PHONY : container\container.obj

# target to build an object file
container\container.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\program.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\program.dir\container\container.cpp.obj
.PHONY : container\container.cpp.obj

container\container.i: container\container.cpp.i
.PHONY : container\container.i

# target to preprocess a source file
container\container.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\program.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\program.dir\container\container.cpp.i
.PHONY : container\container.cpp.i

container\container.s: container\container.cpp.s
.PHONY : container\container.s

# target to generate assembly for a file
container\container.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\program.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\program.dir\container\container.cpp.s
.PHONY : container\container.cpp.s

main.obj: main.cpp.obj
.PHONY : main.obj

# target to build an object file
main.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\program.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\program.dir\main.cpp.obj
.PHONY : main.cpp.obj

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\program.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\program.dir\main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\program.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\program.dir\main.cpp.s
.PHONY : main.cpp.s

models\Flower.obj: models\Flower.cpp.obj
.PHONY : models\Flower.obj

# target to build an object file
models\Flower.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\program.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\program.dir\models\Flower.cpp.obj
.PHONY : models\Flower.cpp.obj

models\Flower.i: models\Flower.cpp.i
.PHONY : models\Flower.i

# target to preprocess a source file
models\Flower.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\program.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\program.dir\models\Flower.cpp.i
.PHONY : models\Flower.cpp.i

models\Flower.s: models\Flower.cpp.s
.PHONY : models\Flower.s

# target to generate assembly for a file
models\Flower.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\program.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\program.dir\models\Flower.cpp.s
.PHONY : models\Flower.cpp.s

models\Plant.obj: models\Plant.cpp.obj
.PHONY : models\Plant.obj

# target to build an object file
models\Plant.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\program.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\program.dir\models\Plant.cpp.obj
.PHONY : models\Plant.cpp.obj

models\Plant.i: models\Plant.cpp.i
.PHONY : models\Plant.i

# target to preprocess a source file
models\Plant.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\program.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\program.dir\models\Plant.cpp.i
.PHONY : models\Plant.cpp.i

models\Plant.s: models\Plant.cpp.s
.PHONY : models\Plant.s

# target to generate assembly for a file
models\Plant.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\program.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\program.dir\models\Plant.cpp.s
.PHONY : models\Plant.cpp.s

models\Shrub.obj: models\Shrub.cpp.obj
.PHONY : models\Shrub.obj

# target to build an object file
models\Shrub.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\program.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\program.dir\models\Shrub.cpp.obj
.PHONY : models\Shrub.cpp.obj

models\Shrub.i: models\Shrub.cpp.i
.PHONY : models\Shrub.i

# target to preprocess a source file
models\Shrub.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\program.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\program.dir\models\Shrub.cpp.i
.PHONY : models\Shrub.cpp.i

models\Shrub.s: models\Shrub.cpp.s
.PHONY : models\Shrub.s

# target to generate assembly for a file
models\Shrub.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\program.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\program.dir\models\Shrub.cpp.s
.PHONY : models\Shrub.cpp.s

models\Tree.obj: models\Tree.cpp.obj
.PHONY : models\Tree.obj

# target to build an object file
models\Tree.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\program.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\program.dir\models\Tree.cpp.obj
.PHONY : models\Tree.cpp.obj

models\Tree.i: models\Tree.cpp.i
.PHONY : models\Tree.i

# target to preprocess a source file
models\Tree.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\program.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\program.dir\models\Tree.cpp.i
.PHONY : models\Tree.cpp.i

models\Tree.s: models\Tree.cpp.s
.PHONY : models\Tree.s

# target to generate assembly for a file
models\Tree.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\program.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\program.dir\models\Tree.cpp.s
.PHONY : models\Tree.cpp.s

utils\utils.obj: utils\utils.cpp.obj
.PHONY : utils\utils.obj

# target to build an object file
utils\utils.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\program.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\program.dir\utils\utils.cpp.obj
.PHONY : utils\utils.cpp.obj

utils\utils.i: utils\utils.cpp.i
.PHONY : utils\utils.i

# target to preprocess a source file
utils\utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\program.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\program.dir\utils\utils.cpp.i
.PHONY : utils\utils.cpp.i

utils\utils.s: utils\utils.cpp.s
.PHONY : utils\utils.s

# target to generate assembly for a file
utils\utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\program.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\program.dir\utils\utils.cpp.s
.PHONY : utils\utils.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... program
	@echo ... algorithms/algorithms.obj
	@echo ... algorithms/algorithms.i
	@echo ... algorithms/algorithms.s
	@echo ... container/container.obj
	@echo ... container/container.i
	@echo ... container/container.s
	@echo ... main.obj
	@echo ... main.i
	@echo ... main.s
	@echo ... models/Flower.obj
	@echo ... models/Flower.i
	@echo ... models/Flower.s
	@echo ... models/Plant.obj
	@echo ... models/Plant.i
	@echo ... models/Plant.s
	@echo ... models/Shrub.obj
	@echo ... models/Shrub.i
	@echo ... models/Shrub.s
	@echo ... models/Tree.obj
	@echo ... models/Tree.i
	@echo ... models/Tree.s
	@echo ... utils/utils.obj
	@echo ... utils/utils.i
	@echo ... utils/utils.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

